services:
  postgres:
    image: postgres:15
    container_name: hck_lms_postgres
    restart: always
    environment:
      POSTGRES_USER: hck_user
      POSTGRES_PASSWORD: hck_password
      POSTGRES_DB: hck_lms
    ports:
      - "5432:5432"
    volumes:
      - hck_lms_postgres_data:/var/lib/postgresql/data

volumes:
  hck_lms_postgres_data: